CREATE TABLE order(
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     userId VARCHAR(200) NOT NULL,
     userEmailAddress VARCHAR(200) NOT NULL,
     amount DECIMAL NOT NULL,
     timestamp TIMESTAMP NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;