CREATE TABLE log(
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     topic VARCHAR(100) NOT NULL,
     body TEXT,
     type ENUM('MESSAGE','SEARCH') NOT NULL,
     timestamp TIMESTAMP NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;